### PR TITLE
feat: conform to PEP561

### PR DESCRIPTION
**Pull request by RaduG**
At the moment, despite the package having PEP484 type annotations, static type checkers will not use them when `vortexasdk` is used in client code. For example, `mypy` will throw an error when inspecting code using `vortexasdk`.

It's very easy to solve the problem - just make it [PEP561](https://www.python.org/dev/peps/pep-0561/) compliant.

### CODE REVIEW

**Review by cvonsteg — APPROVED** [review]

**Comment by KitBurgess** [comment]
@RaduG you'll need to bump the `version.py` file ahead of merging to master. - this is why the check-release-version ci task is failing.

**Comment by RaduG** [comment]
@cvonsteg do I merge or?

**Comment by cvonsteg** [comment]
@RaduG I have little to do with the SDK, so I don't know if ADT or Kit have any objections.  But from my perspective  it looks good to go.

**Comment by RaduG** [comment]
@SeanBarry 
Can we get this in?

**Comment by SeanBarry** [comment]
LGTM.

ADT owns this repo so @JRGranell should give the final green light.

**Pull request closed without merging**
